#!/bin/bash

set -e

DIR=$(realpath "$(dirname "$0")/../")
BACKUP_DIR=$DIR/backup

mkdir -p "$BACKUP_DIR"

cd "$DIR"
for file in *; do
  [[ "$file" =~ (ssh|script|backup|README.*md|.*sample$) ]] && continue
  [ -e "$HOME/.$file" ] && [ ! -L "$HOME/.$file" ] && \
    mv "$HOME/.$file" "$BACKUP_DIR"
  ln -fs "$DIR/$file" "$HOME/.$file"
done

# Install vim-plug as autoload
curl -sfLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# Install vim spell check es
for i in es.latin1.spl es.latin1.sug es.utf-8.spl es.utf-8.sug; do
  curl -sfLo "$HOME/.vim/spell/$i" --create-dirs \
    "http://ftp.vim.org/vim/runtime/spell/$i"
done
# Install vim plugins
vim +PlugUpdate +qall
